version: "3.3"
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: didgksehd
      POSTGRES_DB: deogjil
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-networks
  nestjs_api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    networks:
      - backend-networks
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      backend-networks:



networks:
  backend-networks:

volumes:
  postgres-data:
