version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/cert.pem:/etc/nginx/cert/cert.pem
      - ./cert/key.pem:/etc/nginx/cert/key.pem
    ports:
      - 80:80
      - 443:443
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - nestjs_api
    networks:
      - backend-networks
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: didgksehd
      POSTGRES_DB: deogjil
    networks:
      - backend-networks

  nestjs_api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development

    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 8000:8000
    depends_on:
      - postgres #상단 이름 인식
    networks:
      - backend-networks

networks:
  backend-networks:
