name: test

on: pull_request

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g npm@10.3.0
          npm ci --force

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx create --use && docker buildx build --platform linux/amd64 -t your-image-name:latest .

      - name: Start Docker Compose
        run: sudo docker compose up -d
